# Generated by Django 3.1.7 on 2021-03-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UrlStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(default=None, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('refferer', models.URLField(default='', max_length=100)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.urldata')),
            ],
        ),
    ]
