# Generated by Django 3.1.7 on 2021-03-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
